spring:
  mvc:
    pathmatch:
#      swagger startup fix
      matching-strategy: ant_path_matcher
  datasource:
    trans:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/translate_core?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
      username: root
      password: Han237912
    f95:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/f95_data?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
      username: root
      password: Han237912

  application:
    name: LocalWorkMng

  redis:
    host: localhost
    port: 6379

  net:
    proxy:
      host: 127.0.0.1
      port: 10809

biz:
  f95:
    gameSyncLimiter: 3